name: easy_sidemenu_plus_plus
description: An easy to use side menu (navigation rail) in flutter and can used for navigation
version: 0.1.1
homepage: https://github.com/AbolfazlAbbasiSaeb/sidemenu-Flutter

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:

  assets:
    - assets/